/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.UIManager;

/**
 *
 * @author Anderson Justo
 * @since 13/7/17 - 14:42
 * @version 1.0 beta
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
                setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiFuncionario = new javax.swing.JMenuItem();
        jmiInstrumento = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiClienteM = new javax.swing.JMenuItem();
        jmiFuncionarioM = new javax.swing.JMenuItem();
        jmiInstrumentoM = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmCadastro.setText("Cadastro");

        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCliente);

        jmiFuncionario.setText("Funcionário");
        jmiFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiFuncionario);

        jmiInstrumento.setText("Instrumento");
        jmiInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInstrumentoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiInstrumento);

        jMenuBar1.add(jmCadastro);

        jmManutencao.setText("Manutenção");

        jmiClienteM.setText("Cliente");
        jmiClienteM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteMActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiClienteM);

        jmiFuncionarioM.setText("Funcionário");
        jmiFuncionarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionarioMActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiFuncionarioM);

        jmiInstrumentoM.setText("Instrumento");
        jmiInstrumentoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInstrumentoMActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiInstrumentoM);

        jMenuBar1.add(jmManutencao);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadCliente(){
        UICadCliente ucc = new UICadCliente();
        jAreaTrabalho.add(ucc);
        ucc.setVisible(true);
    }//fecha método
    
    private void abrirCadFuncionario(){
        UICadFuncionario icf = new UICadFuncionario();
        jAreaTrabalho.add(icf);
        icf.setVisible(true);
    }//fecha método
    
    private void abrirCadInstrumento(){
        UICadInstrumento ici = new UICadInstrumento();
        jAreaTrabalho.add(ici);
        ici.setVisible(true);
    }//fecha método
    
    private void abrirManCliente(){
        UIManutencaoCliente umc = new UIManutencaoCliente();
        jAreaTrabalho.add(umc);
        umc.setVisible(true);
    }//fecha método
    
    private void abrirManFuncionario(){
        UIManutencaoFuncionario umf = new UIManutencaoFuncionario();
        jAreaTrabalho.add(umf);
        umf.setVisible(true);
    }//fecha método
    
    private void abrirManInstrumento(){
        UIManutencaoInstrumento umi = new UIManutencaoInstrumento();
        jAreaTrabalho.add(umi);
        umi.setVisible(true);
    }//fecha método
    
    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        abrirCadCliente();
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionarioActionPerformed
        abrirCadFuncionario();
    }//GEN-LAST:event_jmiFuncionarioActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmiFuncionarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionarioMActionPerformed
        // TODO add your handling code here:
        abrirManFuncionario();
    }//GEN-LAST:event_jmiFuncionarioMActionPerformed

    private void jmiClienteMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteMActionPerformed
        // TODO add your handling code here:
        abrirManCliente();
    }//GEN-LAST:event_jmiClienteMActionPerformed

    private void jmiInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInstrumentoActionPerformed
        // TODO add your handling code here:
        abrirCadInstrumento();
    }//GEN-LAST:event_jmiInstrumentoActionPerformed

    private void jmiInstrumentoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInstrumentoMActionPerformed
        // TODO add your handling code here:
        abrirManInstrumento();
    }//GEN-LAST:event_jmiInstrumentoMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Large-Font", "INSERT YOUR LICENSE KEY HERE", "my company");
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiClienteM;
    private javax.swing.JMenuItem jmiFuncionario;
    private javax.swing.JMenuItem jmiFuncionarioM;
    private javax.swing.JMenuItem jmiInstrumento;
    private javax.swing.JMenuItem jmiInstrumentoM;
    // End of variables declaration//GEN-END:variables
}
