/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Funcionario;
import servicos.FuncionarioServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Henrique Peixoto
 * @since 13/07/2017 13:22
 * @version 1.0 EUQUEROTUDOPQEUSOUDOENTE 
 */
public class UICadFuncionario extends javax.swing.JInternalFrame {

    Funcionario f = new Funcionario();

    /**
     * Creates new form UICadFuncionario
     */
    public UICadFuncionario() {
        initComponents();
        jrGerente.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCargo = new javax.swing.ButtonGroup();
        jlpCadastro = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        jlIdade = new javax.swing.JLabel();
        jlLocal = new javax.swing.JLabel();
        jlFilial = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtSalario = new javax.swing.JTextField();
        jtIdade = new javax.swing.JTextField();
        jtLocal = new javax.swing.JTextField();
        jtFilial = new javax.swing.JTextField();
        jrGerente = new javax.swing.JRadioButton();
        jrVendedor = new javax.swing.JRadioButton();
        jlNomeErro = new javax.swing.JLabel();
        jlSalarioErro = new javax.swing.JLabel();
        jlIdadeErro = new javax.swing.JLabel();
        jlLocalErro = new javax.swing.JLabel();
        jlFilialErro = new javax.swing.JLabel();
        jlCargoErro = new javax.swing.JLabel();
        jrEstoquista = new javax.swing.JRadioButton();
        jrCEO = new javax.swing.JRadioButton();
        jrTI = new javax.swing.JRadioButton();
        jrFaxineiro = new javax.swing.JRadioButton();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Funcionário");

        jlpCadastro.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jlNome.setText("Nome");

        jlSalario.setText("Salario");

        jlIdade.setText("Idade");

        jlLocal.setText("Localização");

        jlFilial.setText("Filial");

        jlCargo.setText("Cargo");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtSalarioFocusLost(evt);
            }
        });
        jtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSalarioKeyPressed(evt);
            }
        });

        jtIdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtIdadeFocusLost(evt);
            }
        });
        jtIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtIdadeKeyPressed(evt);
            }
        });

        jtLocal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtLocalFocusLost(evt);
            }
        });
        jtLocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtLocalKeyPressed(evt);
            }
        });

        jtFilial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtFilialFocusLost(evt);
            }
        });
        jtFilial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtFilialKeyPressed(evt);
            }
        });

        bgCargo.add(jrGerente);
        jrGerente.setText("Gerente");
        jrGerente.setActionCommand("Gerente");
        jrGerente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrGerenteKeyPressed(evt);
            }
        });

        bgCargo.add(jrVendedor);
        jrVendedor.setText("Vendedor");
        jrVendedor.setActionCommand("Vendedor");
        jrVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrVendedorKeyPressed(evt);
            }
        });

        bgCargo.add(jrEstoquista);
        jrEstoquista.setText("Estoquista");
        jrEstoquista.setActionCommand("Estoquista");
        jrEstoquista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrEstoquistaKeyPressed(evt);
            }
        });

        bgCargo.add(jrCEO);
        jrCEO.setText("CEO");
        jrCEO.setActionCommand("CEO");
        jrCEO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCEOKeyPressed(evt);
            }
        });

        bgCargo.add(jrTI);
        jrTI.setText("Tecnico Info.");
        jrTI.setActionCommand("Tecnico");
        jrTI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrTIKeyPressed(evt);
            }
        });

        bgCargo.add(jrFaxineiro);
        jrFaxineiro.setText("Faxineiro");
        jrFaxineiro.setActionCommand("Faxineiro");
        jrFaxineiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFaxineiroKeyPressed(evt);
            }
        });

        jlpCadastro.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlSalario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlLocal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlFilial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlCargo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtSalario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtLocal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtFilial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrGerente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrVendedor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlSalarioErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlIdadeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlLocalErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlFilialErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlCargoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrEstoquista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrCEO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrTI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrFaxineiro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpCadastroLayout = new javax.swing.GroupLayout(jlpCadastro);
        jlpCadastro.setLayout(jlpCadastroLayout);
        jlpCadastroLayout.setHorizontalGroup(
            jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCadastroLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(18, 18, 18)
                        .addComponent(jtNome)
                        .addGap(18, 18, 18)
                        .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addComponent(jlSalario)
                        .addGap(18, 18, 18)
                        .addComponent(jtSalario)
                        .addGap(18, 18, 18)
                        .addComponent(jlSalarioErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addComponent(jlFilial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtFilial)
                        .addGap(18, 18, 18)
                        .addComponent(jlFilialErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlLocal)
                                .addGap(18, 18, 18)
                                .addComponent(jtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlLocalErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpCadastroLayout.createSequentialGroup()
                                        .addComponent(jlIdade)
                                        .addGap(28, 28, 28)
                                        .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpCadastroLayout.createSequentialGroup()
                                        .addComponent(jlCargo)
                                        .addGap(18, 18, 18)
                                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrGerente)
                                            .addComponent(jrCEO))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrTI)
                                            .addComponent(jrVendedor))
                                        .addGap(7, 7, 7)
                                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrEstoquista)
                                            .addComponent(jrFaxineiro))))
                                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jlIdadeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCadastroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlCargoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jlpCadastroLayout.setVerticalGroup(
            jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlNome)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlSalario)
                                .addComponent(jtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlSalarioErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlIdade)
                            .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlIdadeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLocal)
                            .addComponent(jtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlLocalErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlFilial)
                        .addComponent(jtFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlFilialErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCargoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCargo)
                        .addComponent(jrGerente)
                        .addComponent(jrVendedor)
                        .addComponent(jrEstoquista)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrTI)
                        .addComponent(jrFaxineiro))
                    .addComponent(jrCEO))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jbCadastrar)
                .addGap(87, 87, 87)
                .addComponent(jbLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpCadastro)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cadastrar() {
        try {

            if (!jtNome.getText().isEmpty()) {
                f.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Erro, nome em branco");

            }
            if (!jtSalario.getText().isEmpty()) {
                f.setSalario(Double.parseDouble(jtSalario.getText()));
            } else {
                throw new NumberFormatException("Erro, salário em branco");

            }
            if (!jtIdade.getText().isEmpty()) {
                f.setIdade(Integer.parseInt(jtIdade.getText()));
            } else {
                throw new NumberFormatException("Erro, idade em branco");

            }
            if (!jtLocal.getText().isEmpty()) {
                f.setLocalizacao(jtLocal.getText());
            } else {
                throw new NumberFormatException("Erro, localização em branco");

            }
            if (!jtFilial.getText().isEmpty()) {
                f.setFilial(jtFilial.getText());
            } else {
                throw new NumberFormatException("Erro, filial em branco");

            }
            if (!jrCEO.isSelected() && !jrEstoquista.isSelected() && !jrFaxineiro.isSelected() && !jrGerente.isSelected()
                    && !jrTI.isSelected() && !jrVendedor.isSelected()) {
                throw new Exception("Selecione o Cargo");
            } else {
                f.setCargo(bgCargo.getSelection().getActionCommand());
            }
            FuncionarioServicos fs = ServicosFactory.getFuncionarioServicos();
            fs.cadastrarFuncionario(f);

            JOptionPane.showMessageDialog(
                    rootPane,
                    "Funcionário cadastrado com sucesso!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage());
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Algum erro ocorreu" + e.getMessage());
        } finally {
            //System.out.println("Passou aqui!");
        }
    }

    private void limpar() {
        jtNome.setText("");
        jtFilial.setText("");
        jtIdade.setText("");
        jtLocal.setText("");
        jtSalario.setText("");
        bgCargo.clearSelection();
        jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtNome.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlFilialErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtFilial.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlIdadeErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtIdade.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlLocalErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtLocal.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlSalarioErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtSalario.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlCargoErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jrGerente.setSelected(true);
        jtNome.grabFocus();
    }
    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        // TODO add your handling code here:
        if (jtNome.getText().isEmpty()) {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtSalario.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSalarioFocusLost
        // TODO add your handling code here:
        if (jtSalario.getText().isEmpty()) {
            jtSalario.setBorder(BorderFactory.createLineBorder(Color.red));
            jlSalarioErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtSalario.setBorder(BorderFactory.createLineBorder(Color.green));
            jlSalarioErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtSalarioFocusLost

    private void jtSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSalarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtIdade.grabFocus();
        }
    }//GEN-LAST:event_jtSalarioKeyPressed

    private void jtIdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtIdadeFocusLost
        // TODO add your handling code here:
        if (jtIdade.getText().isEmpty()) {
            jtIdade.setBorder(BorderFactory.createLineBorder(Color.red));
            jlIdadeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtIdade.setBorder(BorderFactory.createLineBorder(Color.green));
            jlIdadeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtIdadeFocusLost

    private void jtIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtLocal.grabFocus();
        }
    }//GEN-LAST:event_jtIdadeKeyPressed

    private void jtLocalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtLocalFocusLost
        // TODO add your handling code here:
        if (jtLocal.getText().isEmpty()) {
            jtLocal.setBorder(BorderFactory.createLineBorder(Color.red));
            jlLocalErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtLocal.setBorder(BorderFactory.createLineBorder(Color.green));
            jlLocalErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtLocalFocusLost

    private void jtLocalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLocalKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtFilial.grabFocus();
        }
    }//GEN-LAST:event_jtLocalKeyPressed

    private void jtFilialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtFilialFocusLost
        // TODO add your handling code here:
        if (jtFilial.getText().isEmpty()) {
            jtFilial.setBorder(BorderFactory.createLineBorder(Color.red));
            jlFilialErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtFilial.setBorder(BorderFactory.createLineBorder(Color.green));
            jlFilialErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtFilialFocusLost

    private void jtFilialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtFilialKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrGerente.grabFocus();
        }
    }//GEN-LAST:event_jtFilialKeyPressed

    private void jrGerenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrGerenteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrVendedor.grabFocus();
        }
    }//GEN-LAST:event_jrGerenteKeyPressed

    private void jrVendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrVendedorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrEstoquista.grabFocus();
        }
    }//GEN-LAST:event_jrVendedorKeyPressed

    private void jrEstoquistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrEstoquistaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrCEO.grabFocus();
        }
    }//GEN-LAST:event_jrEstoquistaKeyPressed

    private void jrCEOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCEOKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrTI.grabFocus();
        }
    }//GEN-LAST:event_jrCEOKeyPressed

    private void jrTIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrTIKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrFaxineiro.grabFocus();
        }
    }//GEN-LAST:event_jrTIKeyPressed

    private void jrFaxineiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFaxineiroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }
    }//GEN-LAST:event_jrFaxineiroKeyPressed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
            limpar();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCargo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlCargoErro;
    private javax.swing.JLabel jlFilial;
    private javax.swing.JLabel jlFilialErro;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlIdadeErro;
    private javax.swing.JLabel jlLocal;
    private javax.swing.JLabel jlLocalErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JLabel jlSalarioErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpCadastro;
    private javax.swing.JRadioButton jrCEO;
    private javax.swing.JRadioButton jrEstoquista;
    private javax.swing.JRadioButton jrFaxineiro;
    private javax.swing.JRadioButton jrGerente;
    private javax.swing.JRadioButton jrTI;
    private javax.swing.JRadioButton jrVendedor;
    private javax.swing.JTextField jtFilial;
    private javax.swing.JTextField jtIdade;
    private javax.swing.JTextField jtLocal;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtSalario;
    // End of variables declaration//GEN-END:variables
}
