/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Instrumento;
import servicos.ClienteServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Henrique Peixoto
 * @since 11/07/2017 16:01
 * @version 1.0 SÓODADIREITA
 */
public class UICadCliente extends javax.swing.JInternalFrame {

    Cliente c = new Cliente();
    Instrumento i=new Instrumento();

    /**
     * Creates new form UICadCliente
     */
    public UICadCliente() {
        initComponents();
        jrMasculino.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jlpCadastro = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlLocal = new javax.swing.JLabel();
        jlPagamento = new javax.swing.JLabel();
        jlQtd = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtCpf = new javax.swing.JTextField();
        jtLocal = new javax.swing.JTextField();
        jtPagamento = new javax.swing.JTextField();
        jtQtd = new javax.swing.JTextField();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jlNomeErro = new javax.swing.JLabel();
        jlCpfErro = new javax.swing.JLabel();
        jlLocalErro = new javax.swing.JLabel();
        jlPagamentoErro = new javax.swing.JLabel();
        jlQtdErro = new javax.swing.JLabel();
        jlSexoErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cliente");

        jlpCadastro.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jlNome.setText("Nome");

        jlCpf.setText("CPF");

        jlLocal.setText("Localização");

        jlPagamento.setText("Pagamento");

        jlQtd.setText("Quantidade comprada");

        jlSexo.setText("Sexo");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCpfFocusLost(evt);
            }
        });
        jtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCpfKeyPressed(evt);
            }
        });

        jtLocal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtLocalFocusLost(evt);
            }
        });
        jtLocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtLocalKeyPressed(evt);
            }
        });

        jtPagamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPagamentoFocusLost(evt);
            }
        });
        jtPagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPagamentoKeyPressed(evt);
            }
        });

        jtQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQtdFocusLost(evt);
            }
        });
        jtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtQtdKeyPressed(evt);
            }
        });

        bgSexo.add(jrMasculino);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");
        jrMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMasculinoKeyPressed(evt);
            }
        });

        bgSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("Feminino");
        jrFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemininoKeyPressed(evt);
            }
        });

        jlpCadastro.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlLocal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlPagamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlQtd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtLocal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtPagamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtQtd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlCpfErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlLocalErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlPagamentoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlQtdErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlSexoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpCadastroLayout = new javax.swing.GroupLayout(jlpCadastro);
        jlpCadastro.setLayout(jlpCadastroLayout);
        jlpCadastroLayout.setHorizontalGroup(
            jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlCpf)
                                .addGap(18, 18, 18)
                                .addComponent(jtCpf))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addGap(18, 18, 18)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCpfErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addComponent(jlPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPagamentoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addComponent(jlQtd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlQtdErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlSexo)
                                .addGap(18, 18, 18)
                                .addComponent(jrMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrFeminino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlSexoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlLocal)
                                .addGap(18, 18, 18)
                                .addComponent(jtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlLocalErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jlpCadastroLayout.setVerticalGroup(
            jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCpf)
                        .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlCpfErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLocal)
                    .addComponent(jtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLocalErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlPagamento)
                        .addComponent(jtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlPagamentoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlQtd)
                            .addComponent(jtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSexo)
                            .addComponent(jrMasculino)
                            .addComponent(jrFeminino)
                            .addComponent(jlSexoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlQtdErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jbCadastrar)
                .addGap(84, 84, 84)
                .addComponent(jbLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpCadastro)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCpf.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCpfKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtLocal.grabFocus();
        }
    }//GEN-LAST:event_jtCpfKeyPressed

    private void jtLocalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLocalKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           jtPagamento.grabFocus();
        }
    }//GEN-LAST:event_jtLocalKeyPressed

    private void jtPagamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPagamentoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtQtd.grabFocus();
        }
    }//GEN-LAST:event_jtPagamentoKeyPressed

    private void jtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtQtdKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrMasculino.grabFocus();
        }
    }//GEN-LAST:event_jtQtdKeyPressed

    private void jrMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMasculinoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrFeminino.grabFocus();
        }
    }//GEN-LAST:event_jrMasculinoKeyPressed

    private void jrFemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemininoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }
    }//GEN-LAST:event_jrFemininoKeyPressed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        // TODO add your handling code here:
         if (jtNome.getText().isEmpty()) {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCpfFocusLost
        // TODO add your handling code here:
         if (jtCpf.getText().isEmpty()) {
            jtCpf.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCpfErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtCpf.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCpfErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtCpfFocusLost

    private void jtLocalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtLocalFocusLost
        // TODO add your handling code here:
         if (jtLocal.getText().isEmpty()) {
            jtLocal.setBorder(BorderFactory.createLineBorder(Color.red));
            jlLocalErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtLocal.setBorder(BorderFactory.createLineBorder(Color.green));
            jlLocalErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtLocalFocusLost

    private void jtPagamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPagamentoFocusLost
        // TODO add your handling code here:
         if (jtPagamento.getText().isEmpty()) {
            jtPagamento.setBorder(BorderFactory.createLineBorder(Color.red));
            jlPagamentoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtPagamento.setBorder(BorderFactory.createLineBorder(Color.green));
            jlPagamentoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtPagamentoFocusLost

    private void jtQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQtdFocusLost
        // TODO add your handling code here:
         if (jtQtd.getText().isEmpty()) {
            jtQtd.setBorder(BorderFactory.createLineBorder(Color.red));
            jlQtdErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtQtd.setBorder(BorderFactory.createLineBorder(Color.green));
            jlQtdErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtQtdFocusLost

    private void cadastrar() {
        try {

            if (!jtNome.getText().isEmpty()) {
                c.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Erro, nome em branco");

            }
            if (!jtCpf.getText().isEmpty()) {
                c.setCpf(jtCpf.getText());
            } else {
                throw new NumberFormatException("Erro, cpf em branco");

            }
            if (!jtLocal.getText().isEmpty()) {
                c.setLocalizacao(jtLocal.getText());
            } else {
                throw new NumberFormatException("Erro, localização em branco");

            }
            if (!jtPagamento.getText().isEmpty()) {
                c.setPagamento(Double.parseDouble(jtPagamento.getText()));
            } else {
                throw new NumberFormatException("Erro, pagamento em branco");

            }
            if (!jtQtd.getText().isEmpty()) {
                c.setQuantidadeComprada(Integer.parseInt(jtQtd.getText()));
            } else {
                throw new NumberFormatException("Erro, Quantidade em branco");

            }

            if (!jrMasculino.isSelected() && !jrFeminino.isSelected()) {
                throw new Exception("Selecione o sexo");
            } else {
                c.setSexo(bgSexo.getSelection().getActionCommand());
            }

            ClienteServicos cs = ServicosFactory.getClienteServicos();
            cs.cadastrarCliente(c);

            JOptionPane.showMessageDialog(
                    rootPane,
                    "Cliente cadastrado com sucesso!");
            
            /*if(c.getPagamento()<i.getPreco()){
                JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro na compra, você não tem dinheiro suficiente!");
            }else if(c.getPagamento()>i.getPreco()){
                JOptionPane.showMessageDialog(
                    rootPane,
                    "Seu troco: ");
            }else{
                JOptionPane.showMessageDialog(
                    rootPane,
                    "Compra feita com sucesso");
            }*/

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage());
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Algum erro ocorreu" + e.getMessage());
        } finally {
            System.out.println("Passou aqui!");
        }
    }

    private void limpar() {
        jtNome.setText("");
        jtCpf.setText("");
        jtLocal.setText("");
        jtPagamento.setText("");
        jtQtd.setText("");
        bgSexo.clearSelection();
        jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtNome.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlCpfErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtCpf.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlLocalErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtLocal.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlPagamentoErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtPagamento.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlQtdErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtQtd.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlSexoErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jrMasculino.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlCpfErro;
    private javax.swing.JLabel jlLocal;
    private javax.swing.JLabel jlLocalErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlPagamento;
    private javax.swing.JLabel jlPagamentoErro;
    private javax.swing.JLabel jlQtd;
    private javax.swing.JLabel jlQtdErro;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlSexoErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpCadastro;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtLocal;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPagamento;
    private javax.swing.JTextField jtQtd;
    // End of variables declaration//GEN-END:variables
}
