/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Instrumento;
import servicos.InstrumentoServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Anderson Justo
 * @since 13/7/17 - 14:22
 * @version 1.0 beta
 */
public class UICadInstrumento extends javax.swing.JInternalFrame {

    Instrumento i = new Instrumento();

    /**
     * Creates new form UICadInstrumento
     */
    public UICadInstrumento() {
        initComponents();
        jrViolao.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgInstrumentos = new javax.swing.ButtonGroup();
        jlpCadastro = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        jlCor = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jlQtd = new javax.swing.JLabel();
        jlInstrumento = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtPreco = new javax.swing.JTextField();
        jtCor = new javax.swing.JTextField();
        jtMarca = new javax.swing.JTextField();
        jtQtd = new javax.swing.JTextField();
        jrViolao = new javax.swing.JRadioButton();
        jrBaixo = new javax.swing.JRadioButton();
        jlNomeErro = new javax.swing.JLabel();
        jlPrecoErro = new javax.swing.JLabel();
        jlCorErro = new javax.swing.JLabel();
        jlMarcaErro = new javax.swing.JLabel();
        jlQtdErro = new javax.swing.JLabel();
        jlInstrumentoErro = new javax.swing.JLabel();
        jrBateria = new javax.swing.JRadioButton();
        jrViolino = new javax.swing.JRadioButton();
        jrCavaco = new javax.swing.JRadioButton();
        jrUkulele = new javax.swing.JRadioButton();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Instrumento");

        jlpCadastro.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jlNome.setText("Nome");

        jlPreco.setText("Preço");

        jlCor.setText("Cor");

        jlMarca.setText("Marca");

        jlQtd.setText("Quantidade ");

        jlInstrumento.setText("Instrumento");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPrecoFocusLost(evt);
            }
        });
        jtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPrecoKeyPressed(evt);
            }
        });

        jtCor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCorFocusLost(evt);
            }
        });
        jtCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCorKeyPressed(evt);
            }
        });

        jtMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtMarcaFocusLost(evt);
            }
        });
        jtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtMarcaKeyPressed(evt);
            }
        });

        jtQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQtdFocusLost(evt);
            }
        });
        jtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtQtdKeyPressed(evt);
            }
        });

        bgInstrumentos.add(jrViolao);
        jrViolao.setText("Violão/Guitarra");
        jrViolao.setActionCommand("Violao");
        jrViolao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrViolaoKeyPressed(evt);
            }
        });

        bgInstrumentos.add(jrBaixo);
        jrBaixo.setText("Baixo");
        jrBaixo.setActionCommand("Baixo");
        jrBaixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrBaixoKeyPressed(evt);
            }
        });

        bgInstrumentos.add(jrBateria);
        jrBateria.setText("Bateria");
        jrBateria.setActionCommand("Bateria");
        jrBateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrBateriaKeyPressed(evt);
            }
        });

        bgInstrumentos.add(jrViolino);
        jrViolino.setText("Violino");
        jrViolino.setActionCommand("Violino");
        jrViolino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrViolinoKeyPressed(evt);
            }
        });

        bgInstrumentos.add(jrCavaco);
        jrCavaco.setText("Cavaco");
        jrCavaco.setActionCommand("Cavaco");
        jrCavaco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCavacoKeyPressed(evt);
            }
        });

        bgInstrumentos.add(jrUkulele);
        jrUkulele.setText("Ukulele");
        jrUkulele.setActionCommand("Ukulele");
        jrUkulele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrUkuleleKeyPressed(evt);
            }
        });

        jlpCadastro.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlCor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlQtd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlInstrumento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtCor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtQtd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrViolao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrBaixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlPrecoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlCorErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlMarcaErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlQtdErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlInstrumentoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrBateria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrViolino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrCavaco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrUkulele, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpCadastroLayout = new javax.swing.GroupLayout(jlpCadastro);
        jlpCadastro.setLayout(jlpCadastroLayout);
        jlpCadastroLayout.setHorizontalGroup(
            jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCadastroLayout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addGap(18, 18, 18)
                        .addComponent(jtNome)
                        .addGap(18, 18, 18)
                        .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addComponent(jlPreco)
                        .addGap(18, 18, 18)
                        .addComponent(jtPreco)
                        .addGap(18, 18, 18)
                        .addComponent(jlPrecoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addComponent(jlQtd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtQtd)
                        .addGap(18, 18, 18)
                        .addComponent(jlQtdErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlMarca)
                                .addGap(18, 18, 18)
                                .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlMarcaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpCadastroLayout.createSequentialGroup()
                                        .addComponent(jlCor)
                                        .addGap(28, 28, 28)
                                        .addComponent(jtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpCadastroLayout.createSequentialGroup()
                                        .addComponent(jlInstrumento)
                                        .addGap(18, 18, 18)
                                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrViolao)
                                            .addComponent(jrViolino))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrCavaco)
                                            .addComponent(jrBaixo))
                                        .addGap(7, 7, 7)
                                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrBateria)
                                            .addComponent(jrUkulele))))
                                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jlCorErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCadastroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlInstrumentoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jlpCadastroLayout.setVerticalGroup(
            jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlNome)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlPreco)
                                .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlPrecoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCor)
                            .addComponent(jtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCorErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMarca)
                            .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlMarcaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlQtd)
                        .addComponent(jtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlQtdErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlInstrumentoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlInstrumento)
                        .addComponent(jrViolao)
                        .addComponent(jrBaixo)
                        .addComponent(jrBateria)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrCavaco)
                        .addComponent(jrUkulele))
                    .addComponent(jrViolino))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jbCadastrar)
                .addGap(87, 87, 87)
                .addComponent(jbLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpCadastro)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        // TODO add your handling code here:
        if (jtNome.getText().isEmpty()) {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtPreco.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPrecoFocusLost
        // TODO add your handling code here:
        if (jtPreco.getText().isEmpty()) {
            jtPreco.setBorder(BorderFactory.createLineBorder(Color.red));
            jlPrecoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtPreco.setBorder(BorderFactory.createLineBorder(Color.green));
            jlPrecoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtPrecoFocusLost

    private void jtPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCor.grabFocus();
        }
    }//GEN-LAST:event_jtPrecoKeyPressed

    private void jtCorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCorFocusLost
        // TODO add your handling code here:
        if (jtCor.getText().isEmpty()) {
            jtCor.setBorder(BorderFactory.createLineBorder(Color.red));
            jlCorErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtCor.setBorder(BorderFactory.createLineBorder(Color.green));
            jlCorErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtCorFocusLost

    private void jtCorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtMarca.grabFocus();
        }
    }//GEN-LAST:event_jtCorKeyPressed

    private void jtMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMarcaFocusLost
        // TODO add your handling code here:
        if (jtMarca.getText().isEmpty()) {
            jtMarca.setBorder(BorderFactory.createLineBorder(Color.red));
            jlMarcaErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtMarca.setBorder(BorderFactory.createLineBorder(Color.green));
            jlMarcaErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtMarcaFocusLost

    private void jtMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMarcaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtQtd.grabFocus();
        }
    }//GEN-LAST:event_jtMarcaKeyPressed

    private void jtQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQtdFocusLost
        // TODO add your handling code here:
        if (jtQtd.getText().isEmpty()) {
            jtQtd.setBorder(BorderFactory.createLineBorder(Color.red));
            jlQtdErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtQtd.setBorder(BorderFactory.createLineBorder(Color.green));
            jlQtdErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtQtdFocusLost

    private void jtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtQtdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrViolao.grabFocus();
        }
    }//GEN-LAST:event_jtQtdKeyPressed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jrViolaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrViolaoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrBaixo.grabFocus();
        }
    }//GEN-LAST:event_jrViolaoKeyPressed

    private void jrBaixoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrBaixoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrBateria.grabFocus();
        }
    }//GEN-LAST:event_jrBaixoKeyPressed

    private void jrBateriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrBateriaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrViolino.grabFocus();
        }
    }//GEN-LAST:event_jrBateriaKeyPressed

    private void jrViolinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrViolinoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrCavaco.grabFocus();
        }
    }//GEN-LAST:event_jrViolinoKeyPressed

    private void jrCavacoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCavacoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrUkulele.grabFocus();
        }
    }//GEN-LAST:event_jrCavacoKeyPressed

    private void jrUkuleleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrUkuleleKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }
    }//GEN-LAST:event_jrUkuleleKeyPressed

    private void cadastrar() {
        try {

            if (!jtNome.getText().isEmpty()) {
                i.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Erro, nome em branco");

            }
            if (!jtPreco.getText().isEmpty()) {
                i.setPreco(Double.parseDouble(jtPreco.getText()));
            } else {
                throw new NumberFormatException("Erro, preço em branco");

            }
            if (!jtCor.getText().isEmpty()) {
                i.setCor(jtCor.getText());
            } else {
                throw new NumberFormatException("Erro, cor em branco");

            }
            if (!jtMarca.getText().isEmpty()) {
                i.setMarca(jtMarca.getText());
            } else {
                throw new NumberFormatException("Erro, marca em branco");

            }
            if (!jtQtd.getText().isEmpty()) {
                i.setQuantidade(Integer.parseInt(jtQtd.getText()));
            } else {
                throw new NumberFormatException("Erro, quantidade em branco");

            }

            if (!jrBaixo.isSelected() && !jrBateria.isSelected() && !jrCavaco.isSelected() && !jrUkulele.isSelected()
                    && !jrViolao.isSelected() && !jrViolino.isSelected()) {
                throw new Exception("Selecione o instumento");
            } else {
                i.setQualInstrumento(bgInstrumentos.getSelection().getActionCommand());
            }

            InstrumentoServicos is = ServicosFactory.getInstrumentoServicos();
            is.cadastrarInstrumento(i);

            JOptionPane.showMessageDialog(
                    rootPane,
                    "Instrumento cadastrado com sucesso!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage());
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Algum erro ocorreu" + e.getMessage());
        } finally {
            //System.out.println("Passou aqui!");
        }
    }
    private void limpar() {
        jtNome.setText("");
        jtCor.setText("");
        jtMarca.setText("");
        jtPreco.setText("");
        jtQtd.setText("");
        bgInstrumentos.clearSelection();
        jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtNome.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlCorErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtCor.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlMarcaErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtMarca.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlPrecoErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtPreco.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlQtdErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtQtd.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlInstrumentoErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jrViolao.setSelected(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgInstrumentos;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCor;
    private javax.swing.JLabel jlCorErro;
    private javax.swing.JLabel jlInstrumento;
    private javax.swing.JLabel jlInstrumentoErro;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlMarcaErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlPrecoErro;
    private javax.swing.JLabel jlQtd;
    private javax.swing.JLabel jlQtdErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpCadastro;
    private javax.swing.JRadioButton jrBaixo;
    private javax.swing.JRadioButton jrBateria;
    private javax.swing.JRadioButton jrCavaco;
    private javax.swing.JRadioButton jrUkulele;
    private javax.swing.JRadioButton jrViolao;
    private javax.swing.JRadioButton jrViolino;
    private javax.swing.JTextField jtCor;
    private javax.swing.JTextField jtMarca;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPreco;
    private javax.swing.JTextField jtQtd;
    // End of variables declaration//GEN-END:variables
}
